apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay only contains image references for ArgoCD multi-source setup
# Base configuration and sensitive configs are in the private infrastructure repo

images:
- name: ghcr.io/pablitxn/youtube-agent-tools
  newTag: prod
- digest: sha256:d82f74f7ebb805e3e73a2cbf1f9d873e5c82652c5cf82f77ce1a6fd040f05ad5
  name: ghcr.io/pablitxn/youtube-mcp:prod
  newName: ghcr.io/pablitxn/youtube-mcp
