apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay only contains image references for ArgoCD multi-source setup
# Base configuration and sensitive configs are in the private infrastructure repo

images:
- name: ghcr.io/pablitxn/youtube-agent-tools
  newTag: prod
- digest: sha256:8b40939362651c9c17fbaa2afd12b98e696236b35a74a9929226f49c5d443928
  name: ghcr.io/pablitxn/youtube-mcp:prod
  newName: ghcr.io/pablitxn/youtube-mcp
