apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay only contains image references for ArgoCD multi-source setup
# Base configuration and sensitive configs are in the private infrastructure repo

images:
- name: ghcr.io/pablitxn/youtube-agent-tools
  newTag: prod
- digest: sha256:d9c30ec309c37610f071008c8c63abb7aff95de23cf822ad1ef9780a1460d71b
  name: ghcr.io/pablitxn/youtube-mcp:prod
  newName: ghcr.io/pablitxn/youtube-mcp
